# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('ssn', models.IntegerField(db_column='SSN', primary_key=True, serialize=False)),
                ('f_name', models.CharField(blank=True, db_column='F_name', max_length=15, null=True)),
                ('m_name', models.CharField(blank=True, db_column='M_name', max_length=15, null=True)),
                ('l_name', models.CharField(blank=True, db_column='L_name', max_length=15, null=True)),
                ('streat', models.CharField(blank=True, db_column='Streat', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('pin', models.IntegerField(blank=True, db_column='PIN', null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=6, null=True)),
                ('date_of_joining', models.DateField(blank=True, db_column='Date_of_joining', null=True)),
                ('salary', models.IntegerField(blank=True, db_column='Salary', null=True)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminPhoneNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(blank=True, db_column='Phone_no', null=True)),
            ],
            options={
                'db_table': 'admin_phone_no',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'connect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'manages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_duration', models.IntegerField(blank=True, null=True)),
                ('call_type', models.CharField(blank=True, max_length=15, null=True)),
                ('roaming_charges', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('phone_no', models.IntegerField(db_column='Phone_no', primary_key=True, serialize=False)),
                ('f_name', models.CharField(blank=True, db_column='F_name', max_length=15, null=True)),
                ('m_name', models.CharField(blank=True, db_column='M_name', max_length=15, null=True)),
                ('l_name', models.CharField(blank=True, db_column='L_name', max_length=15, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=30, null=True)),
            ],
            options={
                'db_table': 'phone_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOnPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phon_no', models.IntegerField(blank=True, db_column='Phon_no', null=True)),
            ],
            options={
                'db_table': 'service_on_phones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('plan_no', models.IntegerField(db_column='Plan_no', primary_key=True, serialize=False)),
                ('plan_rate', models.CharField(blank=True, db_column='Plan_rate', max_length=10, null=True)),
                ('plan_type', models.CharField(blank=True, db_column='Plan_type', max_length=20, null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelephoneExchange',
            fields=[
                ('exchange_no', models.IntegerField(db_column='Exchange_no', primary_key=True, serialize=False)),
                ('streat', models.CharField(blank=True, db_column='Streat', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('pin', models.IntegerField(blank=True, db_column='PIN', null=True)),
                ('office_name', models.CharField(blank=True, db_column='Office_name', max_length=20, null=True)),
            ],
            options={
                'db_table': 'telephone_exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelephoneOffice',
            fields=[
                ('office_code', models.IntegerField(db_column='Office_code', primary_key=True, serialize=False)),
                ('streat', models.CharField(blank=True, db_column='Streat', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('pin', models.IntegerField(blank=True, db_column='PIN', null=True)),
            ],
            options={
                'db_table': 'telephone_office',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOfficePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(blank=True, db_column='Phone_no', null=True)),
            ],
            options={
                'db_table': 't_office_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('phone_no', models.ForeignKey(db_column='Phone_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='PhoneDirectory.PhoneBook')),
                ('f_name', models.CharField(blank=True, db_column='F_name', max_length=10, null=True)),
                ('m_name', models.CharField(blank=True, db_column='M_name', max_length=10, null=True)),
                ('l_name', models.CharField(blank=True, db_column='L_name', max_length=10, null=True)),
                ('date_of_subscribtion', models.DateField(blank=True, db_column='Date_of_subscribtion', null=True)),
                ('current_location', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(blank=True, max_length=6, null=True)),
                ('streat', models.CharField(blank=True, db_column='Streat', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('pin', models.IntegerField(blank=True, db_column='PIN', null=True)),
            ],
            options={
                'db_table': 'subscriber',
                'managed': False,
            },
        ),
    ]
